/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
public class App {

    // Method to calculate the area of the circle
    public double calculateArea(double radius) {
        return Math.PI * radius * radius;  // Area = π * r^2
    }

    public static void main(String[] args) {
        App app = new App();

        double radius = 5.0;
        double area = app.calculateArea(radius);

      
        System.out.println("The area of the circle with radius " + radius + " is: " + area);
    }
}

