/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
public class App {

    // Method to calculate the area of the circle
    public double calculateArea(double radius) {
        return Math.PI * radius * radius;  // Area = π * r^2
    }

    public static void main(String[] args) {
        // Create an instance of the App class
        App app = new App();

        // Example: Calculate the area of a circle with radius 5
        double radius = 5.0;
        double area = app.calculateArea(radius);

        // Print the area
        System.out.println("The area of the circle with radius " + radius + " is: " + area);
    }
}

