name: CI Pipeline

# Trigger the workflow on pull requests to the develop branch
on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up JDK 21 (to match your toolchain configuration)
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'  # Use Temurin JDK distribution, or choose 'zulu' or 'adopt' if preferred
          cache: gradle  # Enable caching to speed up builds

      # Verify Java version
      - name: Verify Java version
        run: java -version

      # Build the project
      - name: Build the project
        run: ./gradlew build --no-daemon

      # Run tests
      - name: Run tests
        run: ./gradlew test --no-daemon
