name: CI Pipeline

# Trigger the workflow on pull requests to the develop branch
on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      # Build the project
      - name: Build the project
        run: ./gradlew build

      # Run tests after build is successful
      - name: Run tests
        run: ./gradlew test
